[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/users/*"
  to = "https://nodejs211.dszcbaross.edu.hu/user/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200